### PR TITLE
Add meeting minutes from the 2018-08-29 meetup

### PR DESCRIPTION
**Pull request by vine77**
- Added a folder for the month (in a sortable ISO 8601 format)
- Added meeting minutes in a `README.md` (so it shows up easily on GitHub)
- Included some links and projects shared by attendees

### CODE REVIEW

**Comment by obensource** [comment]
@vine77 Wahoo! First PR for WebAudioPDX! 🙌

**Review by obensource — APPROVED** [review]
rad dude
Looks great! 🎉🎉🎉

**Comment by obensource** [comment]
@vine77 would you rather the reviewer merge after review, or approve for you to merge (in general for PRs)? Totally cool either way. 👍

**Comment by vine77** [comment]
@obenspurce I don't have a preference.

Thanks for the sweet GIF!

**Pull request merged**
